version: "3.8"

services:
  exp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ICUB_DOCKER: "${ICUB_DOCKER}"
        LOCAL_USER_ID: ${LOCAL_USER_ID}

    container_name: ${EXP_NAME}:${EXP_VER}
    image: iitschri/${EXP_NAME}:${EXP_VER}

    privileged: true
    stdin_open: true
    tty: true

    device_requests:
     - capabilities:
       - "gpu"
